import type { Metadata } from "next";
import { Inter, Baskervville } from "next/font/google";
import "./globals.css";

const baskerville = Baskervville({
  variable: "--font-baskerville",
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jeudi Studio | Collectif d’artistes digitales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${baskerville.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
